### ISSUE TITLE
Go throug all storie images

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#498] opened 2016-11-28 12:51 UTC
Should now be in 2:1 format, width minimum 800px

**Comment by jonnycoull** [comment] 2016-11-28 13:02
![alecbaldwin](https://cloud.githubusercontent.com/assets/17589853/20669235/fba273f4-b56a-11e6-878b-6485a1e53bbf.jpg)

**Comment by jonnycoull** [comment] 2016-11-28 13:05
ok forget that we'll have to do it manually.

**Comment by jonnycoull** [comment] 2016-12-01 16:51
@lakruzz @illus0r where do these live? so i can edit them?

**Comment by jonnycoull** [comment] 2016-12-01 16:55
So new size is 800x400. ? @illus0r is that right

**Comment by illus0r** [comment] 2016-12-02 11:42
@jonnycoull yep, fixed that [in docs ](https://github.com/Praqma/praqma.com/blob/gh-pages/readme.md#avatar)

Do you want me to cut this new format images to make them 4x3 on the post list? Or what to do next in this issue?

![image](https://cloud.githubusercontent.com/assets/797993/20832820/6c74a0c2-b89d-11e6-89f7-498186fc8810.png)

**Comment by jonnycoull** [comment] 2016-12-02 11:46
I'm fixing the main images to be bigger and 2:1 so once that's complete
(Monday I hope) we can fix these

**Comment by BrucePhable** [comment] 2016-12-02 13:18
@illus0r , @jonnycoull  has these ready where do u want them? please notify me.

**Comment by jonnycoull** [comment] 2016-12-05 09:45
@illus0r where should I put these pics??

**Comment by jonnycoull** [comment] 2016-12-05 11:10
to email @illus0r files to replace.

**Comment by illus0r** [comment] 2016-12-06 12:36
@jonnycoull that's what you sent to me, right?

**Comment by illus0r** [comment] 2016-12-06 12:38
@jonnycoull is it a duplicate of https://github.com/Praqma/praqma.com/issues/497?

**Comment by jonnycoull** [comment] 2016-12-06 13:25
@illus0r this one is the blog post images them selves, #497 refers to making the same ratio image on the stories page.

**Comment by jonnycoull** [comment] 2016-12-12 09:00
@illus0r why isn't this closed?

**Closed** 2016-12-12 11:25 UTC
Labels: Prio 2 - should have, Size 1 - small
