### ISSUE TITLE
search field on stories out of box

### ISSUE THREAD

**Issue by buep** [Praqma/praqma.com#372] opened 2016-09-06 08:03 UTC
![selection_096](https://cloud.githubusercontent.com/assets/1579826/18266089/3340d474-7419-11e6-8354-bfd258a6dc92.png)

**Comment by buep** [comment] 2016-09-06 08:03
Firefox on linux

**Comment by buep** [comment] 2016-09-06 08:04
And it is not only looking strange, I also had to click outside the field to get to search

**Comment by illus0r** [comment] 2016-09-06 12:31
Same on chrome.
Duplicate of #334, but this task is more informative.

**Comment by lakruzz** [comment] 2016-09-21 10:29
@illus0r @jonnycoull let's come up with some design suggestions, how could we solve this in an elegant way?

**Comment by jonnycoull** [comment] 2016-09-21 10:49
can someone direct me to a link where i can have a look please? @lakruzz @illus0r ?

**Comment by jonnycoull** [comment] 2016-09-21 10:51
Do you mean when you type it appears below not inside the box? @buep ?
![screen shot 2016-09-21 at 11 50 41](https://cloud.githubusercontent.com/assets/17589853/18708214/b20315f4-7ff1-11e6-8909-2c2146960a53.png)

**Comment by illus0r** [comment] 2016-09-22 12:45
@jonnycoull yep
@lakruzz what a kind of design suggestion do you mean? Why don't just fix it up? I shouldn't take much time.

**Comment by jonnycoull** [comment] 2016-09-22 12:59
@illus0r yes all it needs is so the copy appears inside so you can handle that Ivan? without need for a mock.

**Comment by lakruzz** [comment] 2016-09-25 18:19
sorry I mistook this for a duplicate of #242

**Comment by lakruzz** [comment] 2016-10-25 14:24
Why is this small task still open? @illus0r

**Comment by jonnycoull** [comment] 2016-10-25 15:25
Full Solution lies within... issue #397 but I'm sure it could be done before all that. @illus0r ive added it to week43

**Comment by lakruzz** [comment] 2016-10-29 15:08
I'm closing this one with 0835c2c (fixes #372 and #414 in one go)

There might be unwanted side effects though I've created #436 investigate if thats's the case

**Closed by lakruzz** 2016-10-29 15:08 UTC
Labels: Prio 1 - must have, Size 1 - small
