### ISSUE TITLE
Training page has bad icons

### ISSUE THREAD

**Issue by hoeghh** [Praqma/praqma.com#199] opened 2016-02-19 12:42 UTC
The icons on the left side of the screen is very confusing.

The icon for Git, Atlassian and Praqma academy are fine. Simple and plain. But the others only disderb more then good is. Keep them simple. The Jenkins logo without extra thinkgs (like text that cant be read anyway and a lightbulb). The two Docker icons are so different that nobody would guess that they are related. Use logoes as icons, not pictures from a submarine.
![praqma com training](https://cloud.githubusercontent.com/assets/11328908/13175947/6ac5ae18-d70e-11e5-80f6-d8263ad77c62.png)

**Comment by lakruzz** [comment] 2016-02-25 19:07
Duplicate of #206

**Comment by hoeghh** [comment] 2016-02-25 19:52
Hej. Jeg vil ikke mene den er en dublet. Den anden sag handler om
størrelser hvor denne om kvaliteten/indholdet af billederne.
Den 25/02/2016 8.07 PM skrev "Lars Kruse" <notifications@github.com>:

**Comment by lakruzz** [comment] 2016-02-25 20:23
@heh ...right!
@monaslarsen - while you are working on #206 can you have an eye on this case too - they are so closely related that the should be done in one go. Please feel free to close this case when you're done with #206 ...if you manage to prettify them indeed :-)

**Comment by lakruzz** [comment] 2016-02-26 09:00
@monaslarsen 

Closed in 6cf072d together with #206

**Closed by lakruzz** 2016-02-26 09:00 UTC
Labels: Prio 1 - must have, Size 1 - small, Status - in progress
